#google/gemma-3-4b-it param meodel


model_id: "meta-llama/Llama-3.2-3B-Instruct"
num_layers: 28
num_heads: 24
head_dim: 128        # hidden_size / num_heads = 2048 / 32
hidden_dim: 3072
intermediate_dim: 8192

# HuggingFace module paths (Llama)
layer_path: "model.layers"
attn_module: "self_attn.o_proj"
mlp_module: "mlp"


# Test config — hook a few middle layers
default_layer_range: [10, 12]
components: ["attn", "mlp"] # ["attn", "mlp", "residual"]

dtype: "float32"    # no GPU, run on CPU
device: "cpu"